### ISSUE TITLE
Issue installing.

### ISSUE THREAD

**Issue by 0xE69** [insaiyancvk/pymusicdl#12]
musicdl
Traceback (most recent call last):
  File "C:\Users\mail\AppData\Local\Programs\Python\Python39\Scripts\musicdl.bat", line 3, in <module>
    from pymusicdl.musicDL import main, check_ffmpeg
  File "C:\Users\mail\AppData\Local\Programs\Python\Python39\lib\site-packages\pymusicdl\__init__.py", line 7, in <module>
    from pymusicdl.musicDL import main
  File "C:\Users\mail\AppData\Local\Programs\Python\Python39\lib\site-packages\pymusicdl\musicDL.py", line 6, in <module>
    logging.basicConfig(filename=LOG_FILE, level=logging.ERROR)
  File "C:\Users\mail\AppData\Local\Programs\Python\Python39\lib\logging\__init__.py", line 2003, in basicConfig
    h = FileHandler(filename, mode,
  File "C:\Users\mail\AppData\Local\Programs\Python\Python39\lib\logging\__init__.py", line 1146, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Users\mail\AppData\Local\Programs\Python\Python39\lib\logging\__init__.py", line 1175, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\mail\\Desktop\\musicDL downloads\\logger.log'

**Comment by DewanshNehra** [comment]
i am also facing the same issue

**Comment by DewanshNehra** [comment]
> i am also facing the same issue

i found the solution for the problem it is becoz there is no folder by the name of `musicDL downloads`  on your desktop just make a folder by this name and you are good to go

**Comment by insaiyancvk** [comment]
@DewanshNehra @Brad-Hunter 
I just updated the code. How careless of me for not testing it properly.
You can update the package with: `pip install pymusicdl -U`

**Comment by 0xE69** [comment]
Closing as this is old.
