### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by DonCappuccin0** [insaiyancvk/pymusicdl#19]
i have this error 

Looks like something went wrong :(
Traceback (most recent call last):
  File "C:\Users\nizar\AppData\Local\Programs\Python\Python39\lib\site-packages\pymusicdl\musicDL.py", line 92, in main
    spotify_downloader().interface()
  File "C:\Users\nizar\AppData\Local\Programs\Python\Python39\lib\site-packages\pymusicdl\modules\spotify_downloader.py", line 198, in interface
    tracks,alburls = self.get_playlist_tracks(sp, plID)
  File "C:\Users\nizar\AppData\Local\Programs\Python\Python39\lib\site-packages\pymusicdl\modules\spotify_downloader.py", line 109, in get_playlist_tracks
    if len(playlist['items'][i]['track']['album']['images']) == 0:
TypeError: 'NoneType' object is not subscriptable

The error has been logged to logger.log file in 'musicDL downloads' on Desktop for reference
Take a screenshort and raise an issue in github or send it to the devs

**Comment by insaiyancvk** [comment]
@DonCappuccin0 Can you send the Spotify playlist you were trying to download? I will try to reproduce the error and fix it

**Comment by DonCappuccin0** [comment]
https://open.spotify.com/playlist/26W48aF16ZoJFGvqjyAKrV?si=1ad9af3c16f04229

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by insaiyancvk** [comment]
I'll look into it.

**Comment by insaiyancvk** [comment]
Hey @DonCappuccin0, I've looked into the code and tried to pinpoint the problem, so I think I kinda figured it out. So there's this song 'Astronomy (8th Light)' in the playlist which is _greyed out_ which means it's either not be available in some regions or got removed because of licensing changes. I solved the issue with the code. I'll release a patch update tomorrow.

**Comment by insaiyancvk** [comment]
@DonCappuccin0 I've updated the code. You can update it locally using: `pip install pymusicdl -U`
