### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by Adith2507** [insaiyancvk/pymusicdl#20]
this is the error i get

Traceback (most recent call last):
  File "C:\Users\advsa\AppData\Local\Programs\Python\Python39\Scripts\musicdl.bat", line 6, in <module>
    main()
  File "C:\Users\advsa\AppData\Local\Programs\Python\Python39\lib\site-packages\pymusicdl\musicDL.py", line 64, in main
    create_dir()
  File "C:\Users\advsa\AppData\Local\Programs\Python\Python39\lib\site-packages\pymusicdl\musicDL.py", line 40, in create_dir
    os.chdir(os.path.expanduser("~/Desktop"))
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\advsa/Desktop'

Can anyone please help me solve this

**Comment by insaiyancvk** [comment]
Did you happen to backup your desktop to onedrive?

**Comment by Adith2507** [comment]
No..

**Comment by insaiyancvk** [comment]
Can you check the output to the following command in command prompt
`python -c "import os;print(os.listdir(os.path.expanduser('~')))" `

**Comment by Adith2507** [comment]
<img width="956" alt="image" src="https://user-images.githubusercontent.com/95995895/145703914-9acc22b8-49e2-4c16-b7d3-dc14c67f1804.png">

**Comment by insaiyancvk** [comment]
Your desktop's location seems to be somewhere else instead of the default directory. Just check if it is in the 'OneDrive' directory.
You can try this command in command prompt for that: `explorer C:\Users\advsa\OneDrive`

**Comment by Adith2507** [comment]
oh yes it is in OneDrive..
um how can i fix this error but?

**Comment by Adith2507** [comment]
do i need to change the location back to default somehow?

**Comment by insaiyancvk** [comment]
There is a dirty trick that will get rid of the bug, it is, create a 'Desktop' directory in C:\Users\<your username>

Otherwise, you just need to change the desktop's location (which is a little complicated but doable)

I'll work on this bug to automatically check for desktop directory that is in onedrive.

**Comment by Adith2507** [comment]
Can u please tell me how to change the desktop's location ?

**Comment by insaiyancvk** [comment]
Check this link:

https://www.addictivetips.com/windows-tips/move-the-desktop-folder-out-of-onedrive-on-windows-10/

**Comment by Adith2507** [comment]
Thank You So much

**Comment by Adith2507** [comment]
The songs seem to be downloaded in webm format

**Comment by insaiyancvk** [comment]
is the desktop moved to the default location? and can you check if you have ffmpeg on your PC.
You can just give `ffmpeg` command in the command prompt. If the output is anything other than 
`'ffmpeg' is not recognized as an internal or external command, operable program or batch file.` then it's in your PATH and we can do other tests to reproduce the problem.

**Comment by Adith2507** [comment]
<img width="909" alt="image" src="https://user-images.githubusercontent.com/95995895/145718026-94efffc0-73e3-423d-a50d-8e2bd9616d1a.png">
<img width="292" alt="image" src="https://user-images.githubusercontent.com/95995895/145718034-36a27a0f-9ea1-47f4-b10b-78196138221c.png">

**Comment by Adith2507** [comment]
Yes i believe i did successfully move the desktop to the default location

**Comment by Adith2507** [comment]
I tried running the program on admin it still downloads the file in webm
I dont have telegram, its fine tho
Thanks for helping me out so much 
i really appreciate it
